### ISSUE TITLE
Does not handle Asciidoc, or parent-dir links

### ISSUE THREAD

**Issue by eskwayrd** [SkyLothar/gitbook-plugin-explicit-url#1]
Hi, I discovered your plugin the other day, and thought it would be useful for my use of GitBook.

Unfortunately, I author my content with Asciidoc pages, and your plugin does not currently support those. Adding that capability in was fairly easy (I'll have a PR available in a day or two).

I also noticed that, in the default GitBook theme, that the up-a-level link that appears when you hover over the page header is implemented as '..', which is also not handled currently. I'm still working on how best to do that.

**Comment by SkyLothar** [comment]
Thanks!
Looking forward for your PR! 😃
